Update setup

diff --git a/script/setup b/script/setup
--- a/script/setup
+++ b/script/setup
@@ -10,6 +10,10 @@ DOTFILESDIR="$(pwd -P)"
 ln -sf "$DOTFILESDIR" "$HOME/.dotfiles"
 cat "$DOTFILESDIR/.bashrc" >> "$HOME/.bashrc"
 
+if [[ $NGROK_AUTHTOKEN ]]; then
+  ngrok config add-authtoken $NGROK_AUTHTOKEN || echo "ngrok auth config failed"
+fi
+
 if [[ -d "/workspaces/github" ]]; then
   export IS_GH_GH=true
   cd "/workspaces/github"
